name: flw

on:
  push:
    branches:
      - main
jobs:
  build:
    name: flw
    runs-on: ubuntu-latest
    steps:
    - name: apt
      run: |
        sudo apt update -q
        sudo apt install -q -y libfuse-dev
    - name: checkout
      uses: actions/checkout@v4.1.1
      with:
        repository: ngkaho1234/fuse-lwext4
    - name: submoudle
      run: |
        cd lwext4
        git submodule update
    - name: fuse
      run: |
        ls lwext4
        make
        make install
