name: flw

on:
  push:
    branches:
      - main-
jobs:
  build:
    name: flw
    runs-on: ubuntu-latest
    steps:
    - name: apt
      run: |
        sudo apt update -q
        sudo apt install -q -y libfuse-dev libacl1-dev p7zip-full
    - name: checkout
      uses: actions/checkout@v4.2.1
      with:
        repository: ngkaho1234/fuse-lwext4
        submodules: recursive
    - name: fuse
      run: |
        ls lwext4
        make
        make install
    - name: test
      run: |
        cd lwext4
        make test
        mkdir mnt
        /usr/local/bin/fuse-lwext4 ext_images/ext4 mnt
        df
        ls mnt
        cd mnt
        mkdir d
        ls
