name: lw

on:
  push:
    branches:
      - main
jobs:
  build:
    name: lw
    runs-on: ubuntu-latest
    steps:
    - name: apt
      run: |
        sudo apt update -q
        sudo apt install -q -y libfuse-dev
    - name: checkout
      uses: actions/checkout@v4.1.1
      with:
        repository: gkostka/lwext4
            
    - name: make
      run: |
        make generic
        cd build_generic
        make
        sudo make install
    - name: test
      run: |
        sudo make test
        cd build_generic/fs_test
        sudo ./lwext4-generic  -i ../../ext_images/ext2 --rw_size 1024 -c 10000
